### ISSUE TITLE
Ticking Player

### ISSUE THREAD

**Issue by preceptor-teeth** [pkmnfrk/megacorp#100]
Player is getting kicked from the server, and this shows up in the logs.  They bought the first rank of the default replenish hunger reward.

'''
net.minecraft.util.ReportedException: Ticking player
at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:459) ~[oq.class:?]
at net.minecraft.network.NetHandlerPlayServer.func_73660_a(NetHandlerPlayServer.java:173) ~[pa.class:?]
at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:209) ~[NetworkDispatcher$1.class:?]
at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:285) ~[gw.class:?]
at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:180) [oz.class:?]
at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:790) [MinecraftServer.class:?]
at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397) [nz.class:?]
at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
at java.lang.Thread.run(Unknown Source) [?:1.8.0_191]
Caused by: java.lang.NoSuchMethodError: net.minecraft.util.FoodStats.func_75119_b(F)V
at com.mike_caron.megacorp.reward.PlayerTickRewards.handleHunger(PlayerTickRewards.java:64) ~[PlayerTickRewards.class:?]
at com.mike_caron.megacorp.reward.PlayerTickRewards.handle(PlayerTickRewards.java:30) ~[PlayerTickRewards.class:?]
at com.mike_caron.megacorp.proxy.CommonProxy.playerTick(CommonProxy.java:98) ~[CommonProxy.class:?]
at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_266_CommonProxy_playerTick_PlayerTickEvent.invoke(.dynamic) ~[?:?]
at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182) ~[EventBus.class:?]
at net.minecraftforge.fml.common.FMLCommonHandler.onPlayerPreTick(FMLCommonHandler.java:365) ~[FMLCommonHandler.class:?]
at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:190) ~[aed.class:?]
at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:382) ~[oq.class:?]
... 9 more
'''

**Comment by pkmnfrk** [comment]
Could you share the rest of the log? I need to know what versions of various things you're running.

**Comment by pkmnfrk** [comment]
Actually, disregard, I see what the issue is.

**Comment by pkmnfrk** [comment]
I'm going to push a release tonight to fix this, but you can also grab it here: https://s3.amazonaws.com/pkmnfrk-minecraft-builds/pkmnfrk/megacorp/28/28.1/MegaCorp-0.2.0-28.jar
